### ISSUE TITLE
Viola doesn't work without internet access

### ISSUE THREAD

**Issue by efccoder** [strath-sdr/rfsoc_sam#14]
Hello,

I've tried viola without my board having internet access.  It pulls up the loading screen but then afterwards nothing shows up.  Has your group tried viola without internet access?  Is there a way for this operate without internet?

thank you.

**Comment by dnorthcote** [comment]
Hi @efccoder,

Thank you for your message. I have tested Voila without an internet connection and it appears to work for several StrathSDR repositories. Are you able to provide some more detail about your setup?

* What is your exact hardware setup?
  * The name of your development board?
  * Do you connect to your board using Ethernet or USB3?
* What is your exact software setup?
  * The version of PYNQ?
  * The version of RFSoC SAM?
* Have you modified your PYNQ install?
  * Please give specific instructions as you how you may have modified your PYNQ install?
  * Did you install any Python packages through pip? If so, what commands did you use?

The above will help me debug your issue further,

Thanks,
David.

**Comment by dnorthcote** [comment]
Hi @efccoder, 

Let me know if you have solved your problem or need further help.

Otherwise, I will close this issue in a few days,

Thanks,
David.

**Comment by dnorthcote** [comment]
Closed issue due to no response.

**Comment by efccoder** [comment]
Hey @dnorthcote, sorry to reopen this topic.  I wasn't able to investigate in the past few weeks.  So it's not the RFSoC that needs internet, it's the computer that needs internet.  I think viola is downloading something and it stores it on the local computer that's interacting with jupyter.  I'm using a ZCU111 and i'm using the latest pynq 2.7 images from your team.  

What I did today is I've launched viola with internet access (ubuntu or windows), once the program loads, I cleared out the cache of my web browser and tried to reload the program.  Nothing comes up.  I've also tried clearing my web browser before launching the application and its the same response, nothing shows up.  I've tried 3 browsers, MS edge, firefox, and brave.  

The program launches when I have internet access, and when I do not clear my browser cache.  It still works without internet so long as I do not clear it.  Is jupyter/viola downloading something?  How can I figure out what its downloading?

**Comment by dnorthcote** [comment]
Hi @efccoder,

Just to confirm, the problem that you are experiencing is the following:
* You are using MS edge / Firefox / Brave to communicate with Jupyter.
* When the PC is not connected to the internet, and voila is launched, the screen is blank.
* The RFSoC internet connectivity is irrelevant.
* If the PC is connected to the internet, and voila is launched, the application loads.
* The application continues to load successfully (even with no PC internet connectivity) during future attempts.
* If you clear the cache, the application fails to load again when the PC is not connected to the internet.

I was able to repeat this issue using the Firefox web browser. However, I was unable to repeat this issue in the Chrome environment. That is, Chrome works successfully regardless of the PC's internet connectivity.

This issue is peculiar, but I do not believe its related to the RFSoC SAM repository and is potentially a core Voila issue or browser problem. Therefore, I'll keep this issue closed for now. If you would like to view the network packets exchanged during Voila setup, you should perhaps use Wireshark.

As a workaround, I would recommend using Chrome for now,

Thanks,
David.

**Comment by efccoder** [comment]
David,

Thanks for investigating.  Chrome doesn't work for me.  I don't normally use chrome and I had to install it in order to try.  I tried it without internet connectivity when I tried it.  It's possible you might not have cleared your cache.  

I think I found the issue but I don't know how to try it.  I'm new to voila myself.  According to voila 0.3.0 docs:

:https://voila.readthedocs.io/en/stable/using.html:

Using third-party Widgets with Voilà¶
By default, Voilà doesn’t serve Jupyter Widgets installed as a classic notebook extension (nbextension).

Instead, it fallbacks to fetching the files from a CDN. This might result in an error (404) in case the custom widget has not been published to npm, or when Voilà runs in an environment without an Internet connection.

To let the Voilà standalone app serve the nbextensions, use the enable_nbextensions flag as follows:

voila --enable_nbextensions=True
When using Voilà as a server extension:

jupyter notebook --VoilaConfiguration.enable_nbextensions=True

where do I run the jupyter notebook command?

**Comment by dnorthcote** [comment]
Hi @efccoder,

You are right, I cleared the Chrome cache (correctly this time) and it failed to work as expected.

It looks like you are trying to run a command line argument. So, to do this, you will need to launch Voila from a terminal.

In Jupyter, open a terminal and type `voila -h`. This will reveal help dialogue for Voila. You will be able to start your investigations from here,

Thanks,
David.
